from fastapi import APIRouter, HTTPException, Depends
from datetime import date
from ai_modules.profit_prediction.predictor import profit_predictor
from app.schemas.forcasting import ProfitPredictionRequest, ProfitPredictionResponse

router = APIRouter(
    prefix="/forecasting",
    tags=["Forecasting & Analytics"]
)

@router.post("/predict-profit", response_model=ProfitPredictionResponse)
async def predict_profit(payload: ProfitPredictionRequest):
    """
    Exposes an API interface to pass retail item configurations and purchase constraints 
    to extract predicted financial output metrics generated by the machine learning engine.
    """
    try:
        # Extract features using exact schema aliases for proper dataframe mapping
        input_data = payload.model_dump(by_alias=True)
        
        # Convert date objects to string formats before pandas transformation steps
        input_data["Order Date"] = str(input_data["Order Date"])
        input_data["Ship Date"] = str(input_data["Ship Date"])
        
        # Call inference service
        predicted_value = profit_predictor.predict(input_data)
        
        return ProfitPredictionResponse(predicted_profit=predicted_value)
        
    except FileNotFoundError as fnf:
        raise HTTPException(status_code=503, detail=str(fnf))
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Inference execution failure: {str(e)}")